#ifndef _LBM_H_
#define _LBM_H_

#include <iostream>

#include "distribution_function/distributionD2Q9.hh"

namespace LBM {

	//fileReader;
	//STLreader;
	//D2Q9
	//D3Q19
	//domain

	namespace containers {
		//Matrix;
	}

	namespace geometry {

	}

	namespace distribution {
		//distributionD2Q9;
	}

	namespace operation {
		//SRT
		//Streaming
	}

	namespace multiphase {

	}

	namespace constantD2Q9 {
		//M InvM w cx cy
	}

} // end of namespace LBM 

#endif // ! #ifndef _LBM_H_